version: '3.8'

services:

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./s3/data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data

  ftp:
    build:
      context: ./ftp/
    image: ftp
    ports:
      - '2121-2130:2121-2130'
    depends_on:
      - s3

  http:
    build:
      context: ./http/
    image: http
    ports:
      - "5000:5000"  # Map Flask server's port to host
    volumes:
      - ./http/data:/data  # Mount the uploads folder to the container to persist uploaded files
#    command: uvicorn main:app --host 0.0.0.0 --port 8000

  clients:
    build:
      context: ./clients/
    image: clients
    depends_on:
      - s3
      - ftp
      - http

