version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data
  s3cmd:
    build:
      context: ./s3/
    image: s3cmd
    depends_on:
      - minio

  ftp:
    build:
      context: ./ftp/
    image: ftp
    ports:
      - '2121-2130:2121-2130'
    depends_on:
      - minio

  http:
    build:
      context: ./http/
    image: http
    ports:
      - "5000:5000"  # Map Flask server's port to host
    volumes:
      - ./uploads:/uploads  # Mount the uploads folder to the container to persist uploaded files
#    command: uvicorn main:app --host 0.0.0.0 --port 8000

