version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data
  s3cmd:
    build:
      context: .
      dockerfile: Dockerfile
    image: s3cmd
    depends_on:
      - minio

