FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        nmap \
        vim \
        s3cmd

COPY .s3cfg /root/

# create a bucket for storing tests data and quit 
ENTRYPOINT ["s3cmd", "mb", "s3://tests-data"]
